spring:
  application:
    name:
      auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_user_db
    username: sports_user
    password: sports_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 0

  jpa:
    open-in-view: false   # harmless for now, we wonâ€™t use JPA

  sql:
    init:
      mode: never

server:
  port: 8080

dgs:
  graphql:
    graphiql:
      enabled: true


logging:
  level:
    com.netflix.graphql.dgs: DEBUG
    org.springframework.graphql: DEBUG
